In [31]:
from tensorflow.examples.tutorials.mnist import input_data

import numpy as np
import random

In [2]:
mnist = input_data.read_data_sets('MNIST_data', one_hot=True)

Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz


In [29]:
x = mnist.train.next_batch(5)[0]
print x.min(), x.max()

0.0 1.0


In [12]:
def get_permutation_matrix(permutations=[(0, 7), (1, 9), (2, 0), (3, 4), (4, 2), (5, 1), (6, 3), (7, 5), (8, 6), (9, 8)]):
    permutation_matrix = np.zeros((10, 10))
    for true_label, noisy_label in permutations:
        permutation_matrix[true_label][noisy_label] = 1
    return permutation_matrix

permutation_matrix = get_permutation_matrix()
print permutation_matrix

[[ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]]


In [22]:
def apply_permutation_matrix(permutation_matrix, p=0.4):
    def fn(a):
        if np.random.uniform() <= p:
            return a.dot(permutation_matrix)
        return a
    return fn

In [23]:
test = np.zeros((1, 10))
test[0][1] = 1
print test

test.dot(permutation_matrix)

[[ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]]


array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.]])

In [24]:
test2 = np.zeros(10)
test2[1] = 1
print test2

[ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]


In [25]:
test2.dot(permutation_matrix)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.])

In [27]:
print x
np.apply_along_axis(apply_permutation_matrix(permutation_matrix, p=0.4), 1, x)

[[ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]]


array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.]])

In [16]:
np.random.uniform()

0.41766785278038676

NameError: name 'tf' is not defined